Repository platzily/platzily-ui, pull requests merged in 2021-10, with the labels that each got.

#2 feature-1 Added initial documentation to define project contributions.
  .github/ISSUE_TEMPLATE/platzily-ui-bug-report---.md
  .github/ISSUE_TEMPLATE/platzily-ui-feature-request---.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: documentation

#9 feaure-8 Created Spike Template for Issues
  .github/ISSUE_TEMPLATE/platzily-ui-spike-report---.md
Labels: documentation, feature

#11 hotfix-10 Fix Spike Template for Issues
  .github/ISSUE_TEMPLATE/platzily-ui-spike-report---.md
Labels: bug
